### ISSUE TITLE
PyCylon doesn't work with Python 3.7

### ISSUE THREAD

**Issue by supunkamburugamuve** [cylondata/cylon#381]
python table_compute_examples.py 
Traceback (most recent call last):
  File "table_compute_examples.py", line 19, in <module>
    import pycylon as cn
  File "/root/anaconda3/envs/myenv/lib/python3.7/site-packages/pycylon/__init__.py", line 26, in <module>
    from pycylon.frame import DataFrame
  File "/root/anaconda3/envs/myenv/lib/python3.7/site-packages/pycylon/frame.py", line 17, in <module>
    from typing import Hashable, List, Dict, Literal, Optional, Sequence, Union, Final
ImportError: cannot import name 'Literal' from 'typing' (/root/anaconda3/envs/myenv/lib/python3.7/typing.py)

**Comment by vibhatha** [comment]
Could this be a Python version issue?

**Comment by chathurawidanage** [comment]
Literal is available in python 3.8+. This should work fine in 3.8+. But
it's just typings, there is no harm in removing it other than a warning
from the IDE.

**Comment by chathurawidanage** [comment]
So should we keep them or remove?

**Comment by vibhatha** [comment]
The test cases are braking if the system has Python 3.7.*.

If the system has 3.7.x (test with the terminal)

My suggestion is to remove since we have sort of agreed to stay with 3.7 to
support proposed work with CuDF, but we can make them as issues to be
replaced
once we migrate to 3.8.

@Supun, @Chathura what do you think?

With Regards,
Vibhatha Abeykoon

**Comment by supunkamburugamuve** [comment]
Yes, lets support Python 3.7. So +1 for removing
